#sqlite3 do not support last_id, customer_fixtures is using it.
development:
  adapter: mysql2
  database: "db/dummy_dev"
test:
  adapter: sqlite3
  database: "db/spree_test.sqlite3"
production:
  adapter: sqlite3
  database: "db/spree_production.sqlite3"

